# Generated by Django 3.2.2 on 2021-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_attendancerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:00 - 9:50', '9:00 - 9:50'), ('9:50 - 10:40', '9:50 - 10:40'), ('10:40 - 11:30', '10:40 - 11:30'), ('11:30 - 12:20', '11:30 - 12:20'), ('12:20 - 1:10', '12:20 - 1:10'), ('2:00 - 2:50', '2:00 - 2:50'), ('2:50 - 3:40', '2:50 - 3:40'), ('3:40 - 4:30', '3:40 - 4:30'), ('4:30 - 5:20', '4:30 - 5:20')], default='11:30 - 12:20', max_length=50),
        ),
    ]
